name: basic demo

on: [push]

jobs: 
  demo: 
    runs-on: ubuntu-latest
    steps:
      - name: a basic echo
        run: echo Hello!
  demo2: 
    runs-on: macos-12
    steps:
      - name: a basic echo
        run: echo Hello!
